### ISSUE TITLE
AttributeError: 'FullDirichletCalibrator' object has no attribute 'weights_init'

### ISSUE THREAD

**Issue by Rogerspy** [dirichletcal/dirichlet_python#1]
When I run `python example/calibration_example.py`, the output is:

```
Training a classifier with cross-validation
Crossval scores: [-0.13321234 -0.05923569 -0.16739947]
Average neg log loss -0.120
Traceback (most recent call last):
  File "calibration_example.py", line 37, in <module>
    gscv.fit(cla_scores_train, y_train)
  File "/home/csong-wps/github/dirichlet_python/venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/csong-wps/github/dirichlet_python/venv/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 765, in fit
    base_estimator = clone(self.estimator)
  File "/home/csong-wps/github/dirichlet_python/venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/csong-wps/github/dirichlet_python/venv/lib/python3.6/site-packages/sklearn/base.py", line 74, in clone
    new_object_params = estimator.get_params(deep=False)
  File "/home/csong-wps/github/dirichlet_python/venv/lib/python3.6/site-packages/sklearn/base.py", line 195, in get_params
    value = getattr(self, key)
AttributeError: 'FullDirichletCalibrator' object has no attribute 'weights_init'
```

I think the possible reason is the incompatible version of the scikit-learn. Which version do you use in the test? (My version is 0.24.0)

**Comment by lesshaste** [comment]
I have the same problem. Is there a workaround?

**Comment by trimeta** [comment]
I believe this issue stems from the increased validation introduced in `scikit-learn 0.23.0`. Specifically, the `clone()` function in `main.py` now uses the `_deprecate_positional_args` decorator, which does additional validation that wasn't previously happening. This validation finds that the `dirichlet_python` classes break a basic assumption of `sklearn`: not all parameters go on to become arguments. This is actually a broader issue with how `dirichlet_python` handles class `__init__()` methods: according to the [sklearn developer guide](https://scikit-learn.org/stable/developers/develop.html#instantiation), the `__init__()` method should *only* read in the parameters and turn them, one-to-one and with identical names, into attributes. If you want to have local variables (like `calibrator_` or `weights_`), those should be created within the `fit()` methods.

One fairly straightforward way to address this would be to modify the `__init__()` methods of the classes in `dirichlet_python` to include a line for each parameter, to ensure it's turned into an attribute. A slightly more advanced fix would be doing that and then also moving all the attributes that *don't* come from parameters out of `__init__()` and into `fit()`. Or adding new parameters and then initializing the attributes from those.

**Comment by perellonieto** [comment]
Thank you all for pointing this problem. And particularly @trimeta for the great explanation. We will try to address this issue as soon as possible.

**Comment by perellonieto** [comment]
I have solved the issue above in commit f36fc1f970809d966325e838d2a1d5d2313245d0

**Comment by shivamtundele** [comment]
@perellonieto Hi, thank you very much for your quick response for @trimeta 's comment. Can you please make these changes on other methods too? Seems like you didnt make change tempscaling, fixed and diagonal dirichlet methods in your commit [`here`](https://github.com/dirichletcal/dirichlet_python/commit/f36fc1f970809d966325e838d2a1d5d2313245d0).

**Comment by perellonieto** [comment]
Thanks again, I think the last commits solved the issues (eg. 270ac2a5a3687710a0a50af423e3b2efd4618343 ).

I will add unittests with full coverage in order to detect these errors.
