### ISSUE TITLE
Typo in DirichletCalibrator

### ISSUE THREAD

**Issue by shivamtundele** [dirichletcal/dirichlet_python#2]
Seem like there's a typo error while running the code even after you fixed other errors in your last commit [f36fc1f](https://github.com/dirichletcal/dirichlet_python/commit/f36fc1f970809d966325e838d2a1d5d2313245d0) @perellonieto .

The error is at [this](https://github.com/dirichletcal/dirichlet_python/blob/150ee9806330c2a9f3269df49ff35a8b5f5d3367/dirichletcal/__init__.py#L36) line.

`/python3.6/site-packages/dirichletcal/__init__.py in fit(self, x, y, x_val, y_val, **kwargs)
     34 
     35     def fit(self, x, y, x_val=None, y_val=None, **kwargs):
---> 36         __self.setup()
     37 
     38         if self.matrix_type == 'diagonal':
NameError: name '_DirichletCalibrator__self' is not defined`

Seems like that's a typo in the fit. It should be self._setup, not _self.setup. Not sure if its the same in other parts of the code.

**Comment by perellonieto** [comment]
Thanks @shivamtundele for checking. Commit 24d6778c1b52fa5b4ca861f3460eb859c4223fb3 fixed the typo that you mentioned.
