### ISSUE TITLE
Still getting error in using all dirichlet methods in mapped calibrators

### ISSUE THREAD

**Issue by shivamtundele** [dirichletcal/dirichlet_python#4]
``` 
lib/python3.6/site-packages/dirichletcal/__init__.py in fit(self, x, y, x_val, y_val, **kwargs)
     34 
     35     def fit(self, x, y, x_val=None, y_val=None, **kwargs):
---> 36         __self.setup()
     37 
     38         if self.matrix_type == 'diagonal':

NameError: name '_DirichletCalibrator__self' is not defined

**Comment by perellonieto** [comment]
I assume you were using the Pypi version which was not updated with the changes. I have now increased the version and uploaded to Pypi version 0.3.dev3 https://pypi.org/project/dirichletcal/

To ensure that we are talking of the same version you could run in the terminal with the enviroment loaded

```
python -c "import dirichletcal; print(dirichletcal.__version__)"
```

which should output

```
0.3.dev3
```

**Comment by shivamtundele** [comment]
I was using pip install from master branch directly. Somehow it worked now. But I ran into another issue with your code. Let me close this issue and open another one! Thanks for your help!
